import { chromium } from '/private/tmp/avsuite-browser-tests/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const errors=[];
try {
    const context=await browser.newContext({viewport:{width:1440,height:1050}});
    const page=await context.newPage();
    page.setDefaultTimeout(15000);
    page.on('dialog', async dialog => { if (dialog.type() === 'beforeunload') await dialog.accept(); });
    await page.request.post('http://127.0.0.1:8769/__test/reset');
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto('http://127.0.0.1:8769/');
    await page.locator('#authLoginUsername').fill('alice');
    await page.locator('#authLoginPassword').fill('test-password');
    await page.locator('#authLoginSubmit').click();
    await page.waitForFunction(()=>document.getElementById('studioSaveStatus')?.dataset.state==='saved').catch(async error=>{console.log(await page.locator('#studioSaveStatus').textContent(),await page.locator('#authLoginError').textContent());throw error;});
    await page.goto('http://127.0.0.1:8769/?session=100');
    await page.waitForFunction(()=>document.querySelector('#clipsCardGrid .clip-card-title')?.value==='Primer clip');
    // Apostrophes in speaker labels must be data, not inline JavaScript.
    page.once('dialog',async dialog=>{assert.match(dialog.message(),/O'Brien/);await dialog.dismiss();});
    await page.locator('.transcript-line-badge').first().click();
    await page.getByRole('button',{name:'Estudio',exact:true}).click();
    await page.locator('[data-tab="editor"]').click();
    await page.locator('#studioTimeline [data-time="end"]').fill('00:02');
    await page.locator('#studioTimeline [data-time="end"]').press('Tab');
    await page.waitForTimeout(1100);
    await page.locator('#studioClose').click();
    await page.waitForFunction(()=>document.getElementById('studioSaveStatus')?.textContent==='Guardado online');
    await page.reload();
    await page.waitForFunction(()=>document.querySelector('#clipsCardGrid input[title="Fin (Out)"]')?.value==='00:02');
    await page.getByRole('button',{name:'Estudio',exact:true}).click();
    await page.locator('[data-tab="brand"]').click();
    await page.locator('#studioBrandName').fill('Marca de prueba');
    await page.locator('#studioBrandTone').fill('Editorial y cercana');
    await page.locator('#studioBrandForm button[type="submit"]').click();
    await page.locator('[data-tab="images"]').click();
    await page.locator('#studioImagePrompt').fill('Una miniatura dorada para un podcast');
    await page.locator('#studioImageForm button[type="submit"]').click();
    await page.waitForSelector('#studioImageResults img[src^="blob:"]');
    assert.equal(await page.locator('#studioImageResults img').count(),1);
    await page.locator('[data-tab="campaign"]').click();
    await page.locator('#studioCampaignBrief').fill('Promocionar un episodio');
    await page.locator('#studioCampaignForm button[type="submit"]').click();
    await page.waitForSelector('#studioCampaignResults .studio-job');
    await page.getByRole('button',{name:'Aplicar títulos y copies a los clips'}).click();
    await page.locator('#studioClose').click();
    assert.equal(await page.locator('#clipsCardGrid .clip-card-title').inputValue(),'Título 1');
    await page.waitForFunction(()=>document.getElementById('studioSaveStatus')?.textContent==='Guardado online');
    await page.goto('http://127.0.0.1:8769/historial');
    await page.waitForSelector('.session-item-full');
    assert.equal(await page.locator('.session-item-full').count(),1);
    assert.match(await page.locator('.session-item-full-title').textContent(),/Prueba del estudio/);
    console.log('Initial studio checks passed.');
    // Two tabs must never silently overwrite each other's saved revision.
    const secondTab=await context.newPage();secondTab.setDefaultTimeout(15000);secondTab.on('dialog',async dialog=>{if(dialog.type()==='beforeunload')await dialog.accept();});secondTab.on('pageerror',error=>errors.push(error.message));
    await secondTab.goto('http://127.0.0.1:8769/?session=100');
    await secondTab.waitForFunction(()=>document.querySelector('#clipsCardGrid .clip-card-title')?.value==='Título 1');
    await page.getByRole('button',{name:'Estudio',exact:true}).click();
    await page.locator('[data-tab="brand"]').click();await page.locator('#studioBrandName').fill('Marca actualizada');
    await page.locator('#studioBrandForm button[type="submit"]').click();
    await page.waitForFunction(()=>document.getElementById('studioSaveStatus')?.textContent==='Guardado online');
    await secondTab.locator('#clipsCardGrid .clip-card-title').fill('Cambio de otra pestaña');
    await secondTab.locator('#clipsCardGrid .clip-card-title').press('Tab');
    await secondTab.waitForFunction(()=>document.getElementById('studioSaveStatus')?.dataset.state==='conflict');
    const remote=await page.evaluate(async()=>{const response=await fetch('/studio/workspace',{headers:{'X-API-Key':localStorage.getItem('api_access_key')}});return response.json();});
    assert.equal(remote.document.brand.name,'Marca actualizada');
    assert.equal(remote.document.sessions[0].data.editor.clips[0].label,'Título 1');
    console.log('Two-tab conflict checks passed.');
    await context.close();
    // A new browser and account cannot see Alice's workspace.
    const other=await browser.newContext({viewport:{width:390,height:844}});
    const mobile=await other.newPage();mobile.on('pageerror',error=>errors.push(error.message));
    await mobile.goto('http://127.0.0.1:8769/');
    await mobile.locator('#authLoginUsername').fill('bob');await mobile.locator('#authLoginPassword').fill('test-password');
    await mobile.locator('#authLoginSubmit').click();
    await mobile.waitForFunction(()=>document.getElementById('studioSaveStatus')?.textContent.includes('sincronizado'));
    await mobile.getByRole('button',{name:'Estudio',exact:true}).click();
    await mobile.locator('[data-tab="jobs"]').click();
    await mobile.waitForFunction(()=>document.getElementById('studioJobs')?.textContent.includes('Todavía no hay trabajos'));
    await mobile.locator('[data-tab="images"]').click();
    await fs.mkdir('test-results',{recursive:true});
    await mobile.screenshot({path:'test-results/studio-mobile.png'});
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
    assert.deepEqual(errors,[]);
    console.log('Browser checks passed: login, private workspace, reload/autosave, images, campaigns, history, two-tab conflicts, mobile.');
    await other.close();
    const guestContext=await browser.newContext({viewport:{width:390,height:844}});
    const guest=await guestContext.newPage();guest.on('pageerror',error=>errors.push(error.message));
    await guest.goto('http://127.0.0.1:8769/');
    await guest.getByRole('button',{name:'Entrar sin cuenta · FREE'}).click();
    await guest.waitForFunction(()=>document.getElementById('navAccountLabel')?.textContent==='Invitado · FREE');
    assert.match(await guest.locator('#studioSaveStatus').textContent(),/Sin historial/);
    assert.equal(await guest.locator('a[href="/historial"]').isVisible(),false);
    const authenticated=await guest.evaluate(async()=>{
        const token=sessionStorage.getItem('guest_access_key');
        const response=await fetch('/auth/check',{headers:{'X-API-Key':token}});
        return {user:await response.json(),localToken:localStorage.getItem('api_access_key')};
    });
    assert.equal(authenticated.user.plan,'FREE');assert.equal(authenticated.localToken,null);
    await guest.evaluate(async()=>{
        const {saveSession}=await import('/js/modules/sessions.js');
        saveSession({title:'Análisis temporal',raw_timeline:'TIMESTAMP: 00:00\nSPEAKER: Persona\nDIALOGUE: Material sintético para probar el acceso sin cuenta.'});
    });
    assert.equal(await guest.evaluate(()=>Object.keys(localStorage).some(key=>key.includes('__guest__'))),false);
    await guest.getByRole('button',{name:'Estudio',exact:true}).click();
    assert.equal(await guest.locator('[data-tab="sync"]').isVisible(),false);
    assert.equal(await guest.locator('[data-tab="jobs"]').isVisible(),false);
    await guest.locator('#studioClose').click();
    await guest.reload();
    await guest.waitForFunction(()=>document.getElementById('navAccountLabel')?.textContent==='Invitado · FREE');
    assert.equal(await guest.evaluate(async()=>(await import('/js/utils/storage.js')).getSessions().length),0);
    assert.equal(await guest.evaluate(async()=>(await import('/js/state.js')).state.currentData),null);
    await guest.goto('http://127.0.0.1:8769/historial');
    await guest.waitForURL('http://127.0.0.1:8769/');
    assert.deepEqual(errors,[]);
    console.log('Guest checks passed: public entry, FREE limits, no saved history, reload, private tabs.');
    await guestContext.close();
} finally {await browser.close();}
